apiVersion: v1
kind: ServiceAccount
metadata:
    name: sonqo
    namespace: mongodb-poc
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    namespace: mongodb-poc
    name: sonqo-role
rules:
    - apiGroups: ['*']
      resources: ['*']
      verbs: ['*']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: sonqo-controller
    namespace: mongodb-poc
subjects:
    - kind: ServiceAccount
      name: sonqo
      apiGroup: ''
      namespace: mongodb-poc
roleRef:
    kind: ClusterRole
    name: sonqo-role
    apiGroup: ''
