apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
    name: opsmanager
spec:
    replicas: 1
    version: 4.4.4
    adminCredentials: opsmanager-creds
    externalConnectivity:
        type: LoadBalancer
    applicationDatabase:
        members: 3
        version: 4.4.4-ent
    backup:
        enabled: true
        opLogStores:
            - name: oplog1
              mongodbResourceRef:
                  name: my-oplog-db
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: mongodb-ops-manager
                          image: quay.io/mongodb/mongodb-enterprise-ops-manager:4.4.4
                          resources:
                              requests:
                                  memory: 1G
                              limits:
                                  memory: 1G
