apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
    name: mongodb-sharded
spec:
    shardCount: 2
    mongodsPerShardCount: 1
    mongosCount: 1
    configServerCount: 1
    version: 4.4.4-ent
    opsManager:
        configMapRef:
            name: mongodb-configmap
    credentials: programmatic-api-key
    type: ShardedCluster
    persistent: true
    configSrvPodSpec:
        podTemplate:
            spec:
                nodeSelector:
                    status: master
    mongosPodSpec:
        podTemplate:
            spec:
                nodeSelector:
                    status: master
    shardPodSpec:
        podTemplate:
            spec:
                nodeSelector:
                    status: worker
                topologySpreadConstraints:
                    - maxSkew: 1
                      topologyKey: kubernetes.io/hostname
                      whenUnsatisfiable: DoNotSchedule
                      labelSelector:
                          matchLabels:
                              app: mongodb-sharded-sh
