---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: mongodb-enterprise-appdb
    namespace: mongodb-mvp
---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: mongodb-enterprise-database-pods
    namespace: mongodb-mvp
---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: mongodb-enterprise-ops-manager
    namespace: mongodb-mvp
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: mongodb-enterprise-appdb
    namespace: mongodb-mvp
rules:
    - apiGroups:
          - ''
      resources:
          - secrets
      verbs:
          - get
    - apiGroups:
          - ''
      resources:
          - pods
      verbs:
          - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: mongodb-enterprise-appdb
    namespace: mongodb-mvp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: mongodb-enterprise-appdb
subjects:
    - kind: ServiceAccount
      name: mongodb-enterprise-appdb
      namespace: mongodb-mvp
