apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
    name: mongodb-sharded
spec:
    shardCount: 3
    mongodsPerShardCount: 1
    mongosCount: 3
    configServerCount: 3
    version: 4.4.4-ent
    opsManager:
        configMapRef:
            name: mongodb-configmap
    credentials: programmatic-api-key
    type: ShardedCluster
    persistent: true
    configSrvPodSpec:
        topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
    mongosPodSpec:
        topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
    shardPodSpec:
        topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
