apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            containers:
                - name: express
                  env:
                      - name: MONGO_URL
                        value: mongodb://mongo-service:27017/express
                  resources: {}
                  image: sonqo/express-app:latest
                  ports:
                      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: express-service
spec:
    selector:
        app: express
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30042
