apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
    labels:
        app: express
spec:
    replicas: 2
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: zone
                  whenUnsatisfiable: DoNotSchedule
                  labelSelector:
                      matchLabels:
                          app: express
            containers:
                - name: express
                  env:
                      - name: MONGO_URL
                        value: mongodb://mongo-service:27017/express?replicaSet=rs
                  resources: {}
                  image: sonqo/express-app:latest
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: express-service
    labels:
        app: express
spec:
    selector:
        app: express
    type: NodePort
    ports:
        - name: http
          protocol: TCP
          port: 80
          nodePort: 30042
          targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: express-exposed
    labels:
        app: express
spec:
    selector:
        app: express
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 3000
    type: LoadBalancer
