apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
    namespace: thesis-nmspc
spec:
    replicas: 1
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: zone
                  whenUnsatisfiable: DoNotSchedule
                  labelSelector:
                      matchLabels:
                          app: express
            containers:
                - name: express
                  env:
                      - name: MONGO_URL
                        value: mongodb://mongo-service:27017/express
                  resources: {}
                  image: sonqo/express-app:latest
                  ports:
                      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: express-service
    namespace: thesis-nmspc
spec:
    selector:
        app: express
    type: NodePort
    ports:
        - name: http
          protocol: TCP
          port: 80
          nodePort: 30042
          targetPort: 3000
