apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-pvc
    namespace: thesis-nmspc
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 500Mi
