apiVersion: v1
kind: Secret
metadata:
    name: opsmanager-admin
type: Opaque
data:
    Username: cm9vdA== # root
    Password: QWRtaW4tcm9vdDQy # Admin-root42
    FirstName: c29ucW8= # sonqo
    LastName: bnR1YQ== # ntua
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
    name: mongodb-enterprise-opsmanager
spec:
    replicas: 1
    version: 5.0.0
    adminCredentials: opsmanager-admin
    externalConnectivity:
        type: LoadBalancer
    applicationDatabase:
        members: 3
        version: 4.4.4-ent
    backup:
        enabled: false
