apiVersion: v1
kind: Secret
metadata:
    name: opsmanager-admin
type: Opaque
data:
    Username: cm9vdA== # root
    Password: QWRtaW4tcm9vdDQy # Admin-root42
    FirstName: c29ucW8= # sonqo
    LastName: bnR1YQ== # ntua
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
    name: mongodb-enterprise-opsmanager
spec:
    replicas: 1
    version: 5.0.0
    adminCredentials: opsmanager-admin
    externalConnectivity:
        type: LoadBalancer
    applicationDatabase:
        members: 3
        version: 4.4.4-ent
        podSpec:
            podTemplate:
                spec:
                    nodeSelector:
                        status: worker
                    topologySpreadConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: DoNotSchedule
                          labelSelector:
                              matchLabels:
                                  pod-anti-affinity: mongodb-enterprise-opsmanager-db
    backup:
        enabled: false
