apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo
spec:
    serviceName: mongo-headless
    replicas: 3
    selector:
        matchLabels:
            role: mongo
    template:
        metadata:
            labels:
                role: mongo
                environment: test
        spec:
            serviceAccountName: mongo
            automountServiceAccountToken: true
            terminationGracePeriodSeconds: 10
            containers:
                - name: mongo
                  image: mongo:4.0
                  command:
                      - mongod
                  args:
                      - '--replSet=rs'
                      - '--bind_ip=0.0.0.0'
                  ports:
                      - containerPort: 27017
                  volumeMounts:
                      - name: mongo-volume
                        mountPath: /data/db
                - name: mongo-sidecar
                  image: morphy/k8s-mongo-sidecar
                  env:
                      - name: KUBERNETES_POD_LABELS
                        value: 'role=mongo,environment=test'
                      - name: KUBE_NAMESPACE
                        value: 'express'
                      - name: KUBERNETES_SERVICE_NAME
                        value: 'mongo-headless'
    volumeClaimTemplates:
        - metadata:
              name: mongo-volume
          spec:
              accessModes: ['ReadWriteOnce']
              resources:
                  requests:
                      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mongo-service
spec:
    selector:
        role: mongo
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
