apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: mongo-sc
spec:
    shardCount: 2
    mongodsPerShardCount: 2
    mongosCount: 2
    configServerCount: 2
    version: '4.2.2'
    type: ShardedCluster
    security:
        authentication:
            modes: ['SCRAM']
    users:
        - name: user
          db: app
          passwordSecretRef: # a reference to the secret that will be used to generate the user's password
              name: user-password
          roles:
              - name: clusterAdmin
                db: admin
              - name: dbAdminAnyDatabase
                db: admin
              - name: readWriteAnyDatabase
                db: admin
              - name: userAdminAnyDatabase
                db: admin
          scramCredentialsSecretName: my-scram
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
