apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo
spec:
    selector:
        matchLabels:
            app: mongo
    serviceName: 'mongo'
    replicas: 3
    template:
        metadata:
            labels:
                app: mongo
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: mongo
                  image: mongo:4.0
                  command:
                      - mongod
                      - '--bind_ip_all'
                      - '--replSet'
                      - rs0
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongo-secret
                                key: mongo-root-username
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongo-secret
                                key: mongo-root-password
                  volumeMounts:
                      - name: mongo-volume
                        mountPath: /data/db
    volumeClaimTemplates:
        - metadata:
              name: mongo-volume
          spec:
              accessModes:
                  - ReadWriteMany
              resources:
                  requests:
                      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mongo-service
spec:
    selector:
        app: mongo
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
