apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
    labels:
        app: express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            nodeSelector:
                status: master
            topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: kubernetes.io/hostname
                  whenUnsatisfiable: DoNotSchedule
                  labelSelector:
                      matchLabels:
                          app: express
            containers:
                - name: express
                  env:
                      - name: MONGO_URL
                        value: mongodb://user:root@mongodb-service.mongodb-mvp:27017/mvp?authMechanism=SCRAM-SHA-256&authSource=admin&readPreference=nearest
                  image: sonqo/express-app:latest
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          cpu: 500m
                      requests:
                          cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
    name: express-ext
    labels:
        app: express
spec:
    selector:
        app: express
    type: LoadBalancer
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 3000
